### ISSUE TITLE
Determine possible cloud hosting solutions

### ISSUE THREAD

**Issue by eric-K1** [TechnionYP5779/eduval#1]
This project will involve an app that saves data on the cloud. We need to investigate different options that allow us to host a database and server-side logic.

**Comment by anny234** [comment]
**Azure** - Microsoft Azure is a cloud computing service. It is used for building, testing, deploying, and managing applications. Azure provides Software as a service, Platform as a service and Infrastructure as a service. Also, it supports many different languages, tools, and frameworks.
**Firebase** - It builds apps fast, without managing infrastructure. One platform, with products that work together.
**Google Cloud** - It is a suite of cloud computing services. It provides a set of management tools. Also, it provides a series of modular cloud services. Google Cloud services including computing, data storage, data analytics and machine learning.
**AWS** - It provides on-demand cloud computing platforms to individuals, companies, and governments, on the paid subscription basis. It is a choice of operating systems, networking, and pre-loaded application software.

**Comment by DanielaDii** [comment]
Checked prices for firebase. It seems that free "spark" plan is ok for our needs
https://firebase.google.com/pricing/

**Comment by anny234** [comment]
### Conclusion

Our current conclusion is that we should use Firebase. The free plan offers a real time communication (while the current alpha with AWS has a very high latency). It has many tutorials online, so it will be easier to learn and start working with it.
