### ISSUE TITLE
DB functions for student site

### ISSUE THREAD

**Issue by yanivbaldi** [TechnionYP5779/eduval#34]
- [x] get student's name by id
- [x] get student's classes (course name and id) list by id
- [x] get list of lessons (date and Emons) by student's id and class name 
- [x] get Emon sum for class id and student id 
- [x] post message from the student (in specific lesson)
- [x] get messages and updates (Emons, Emojies) from the teacher to the student (in specific lesson)
- [x] update personal info in Registration
- [x] get info by id when updating personal info
- [x] get values in the end of the lesson

**Comment by eladyundler** [comment]
blabla
