### ISSUE TITLE
Fix Auth0 login

### ISSUE THREAD

**Issue by eric-K1** [TechnionYP5779/eduval#98]
Currently login is often blocked due to third party cookies. Use Auth0's universal login page.

**Comment by eric-K1** [comment]
https://auth0.com/docs/libraries/custom-signup

**Comment by anny234** [comment]
Custom login won't fix because of [cross-origin](https://auth0.com/docs/cross-origin-authentication).
Need to use [universal-login](https://auth0.com/docs/quickstart/spa/react) instead.
